version: 2
jobs:
  build:
    working_directory: ~/repo
    machine: true
    branches:
      only:
        - master
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: build docker image
          command: |
            echo "deploying to development environment"
            docker build -t experimentality-front .
            docker tag experimentality-front manuelgomezo/experimentality-front
            docker push manuelgomezo/experimentality-front
